'use client';
import React, { useState } from 'react';
import VerseCard from '@/components/shared/VerseCard';
import SummaryCard from '@/components/shared/SummaryCard';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

interface SurahAtTawbahViewProps {
  goBack: () => void;
}

const verses = [
    { number: "9:1", arabic: "Placeholder", lao: "Placeholder", english: "[This is a declaration of] disassociation, from Allah and His Messenger, to those with whom you had made a treaty among the polytheists." },
    { number: "9:2", arabic: "Placeholder", lao: "Placeholder", english: "So travel freely, [O disbelievers], throughout the land [during] four months but know that you cannot cause failure to Allah and that Allah will disgrace the disbelievers." },
    { number: "9:3", arabic: "Placeholder", lao: "Placeholder", english: "And [it is] an announcement from Allah and His Messenger to the people on the day of the greater pilgrimage that Allah is disassociated from the disbelievers, and [so is] His Messenger. So if you repent, that is best for you; but if you turn away - then know that you will not cause failure to Allah. And give tidings to those who disbelieve of a painful punishment." },
    { number: "9:4", arabic: "Placeholder", lao: "Placeholder", english: "Excepted are those with whom you made a treaty among הpolytheists and then they have not been deficient toward you in anything or supported anyone against you; so complete for them their treaty until their term [has ended]. Indeed, Allah loves the righteous [who are mindful of Him]." },
    { number: "9:5", arabic: "Placeholder", lao: "Placeholder", english: "And when the sacred months have passed, then kill the polytheists wherever you find them and capture them and besiege them and sit in wait for them at every place of ambush. But if they should repent, establish prayer, and give zakah, let them [go] on their way. Indeed, Allah is Forgiving and Merciful." },
    { number: "9:6", arabic: "Placeholder", lao: "Placeholder", english: "And if any one of the polytheists seeks your protection, then grant him protection so that he may hear the words of Allah. Then deliver him to his place of safety. That is because they are a people who do not know." },
    { number: "9:7", arabic: "Placeholder", lao: "Placeholder", english: "How can there be for the polytheists a treaty in the sight of Allah and with His Messenger, except for those with whom you made a treaty at al-Masjid al-Haram? So as long as they are upright toward you, be upright toward them. Indeed, Allah loves the righteous [who are mindful of Him]." },
    { number: "9:8", arabic: "Placeholder", lao: "Placeholder", english: "How [can there be a treaty] while, if they gain dominance over you, they do not observe concerning you any pact of kinship or covenant of protection? They satisfy you with their mouths, but their hearts refuse, and most of them are defiantly disobedient." },
    { number: "9:9", arabic: "Placeholder", lao: "Placeholder", english: "They have exchanged the signs of Allah for a small price and averted [people] from His way. Indeed, it was evil that they were doing." },
    { number: "9:10", arabic: "Placeholder", lao: "Placeholder", english: "They do not observe toward a believer any pact of kinship or covenant of protection. And it is they who are the transgressors." },
    { number: "9:11", arabic: "Placeholder", lao: "Placeholder", english: "But if they repent, establish prayer, and give zakah, then they are your brothers in religion. And We detail the verses for a people who know." },
    { number: "9:12", arabic: "Placeholder", lao: "Placeholder", english: "And if they break their oaths after their treaty and defame your religion, then fight the leaders of disbelief, for indeed, there are no oaths [sacred] to them; [fight them that] they might cease." },
    { number: "9:13", arabic: "Placeholder", lao: "Placeholder", english: "Would you not fight a people who broke their oaths and determined to expel the Messenger, and they had begun [the attack upon] you the first time? Do you fear them? But Allah has more right that you should fear Him, if you are [truly] believers." },
    { number: "9:14", arabic: "Placeholder", lao: "Placeholder", english: "Fight them; Allah will punish them by your hands and will disgrace them and give you victory over them and satisfy the breasts of a believing people" },
    { number: "9:15", arabic: "Placeholder", lao: "Placeholder", english: "And remove the fury in their hearts. And Allah turns in forgiveness to whom He wills; and Allah is Knowing and Wise." },
    { number: "9:16", arabic: "Placeholder", lao: "Placeholder", english: "Do you think that you will be left [as you are] while Allah has not yet made evident those of you who strive in His cause and do not take other than Allah, His Messenger and the believers as intimates? And Allah is Acquainted with what you do." },
    { number: "9:17", arabic: "Placeholder", lao: "Placeholder", english: "It is not for the polytheists to maintain the masjids of Allah [while] witnessing against themselves with disbelief. [For] those, their deeds have become worthless, and in the Fire they will abide eternally." },
    { number: "9:18", arabic: "Placeholder", lao: "Placeholder", english: "The masjids of Allah are only to be maintained by those who believe in Allah and the Last Day and establish prayer and give zakah and do not fear except Allah, for it is expected that those will be of the [rightly] guided." },
    { number: "9:19", arabic: "Placeholder", lao: "Placeholder", english: "Have you made the providing of water for the pilgrim and the maintenance of al-Masjid al-Haram equal to [the deeds of] one who believes in Allah and the Last Day and strives in the cause of Allah? They are not equal in the sight of Allah. And Allah does not guide the wrongdoing people." },
    { number: "9:20", arabic: "Placeholder", lao: "Placeholder", english: "The ones who have believed, emigrated and striven in the cause of Allah with their wealth and their lives are greater in rank in the sight of Allah. And it is those who are the attainers [of success]." },
    { number: "9:21", arabic: "Placeholder", lao: "Placeholder", english: "Their Lord gives them good tidings of mercy from Him and approval and of gardens for them wherein is enduring pleasure." },
    { number: "9:22", arabic: "Placeholder", lao: "Placeholder", english: "Abiding therein forever. Indeed, Allah has with Him a great reward." },
    { number: "9:23", arabic: "Placeholder", lao: "Placeholder", english: "O you who have believed, do not take your fathers or your brothers as allies if they have preferred disbelief over belief. And whoever does so among you - then it is those who are the wrongdoers." },
    { number: "9:24", arabic: "Placeholder", lao: "Placeholder", english: "Say, [O Muhammad], 'If your fathers, your sons, your brothers, your wives, your relatives, wealth which you have obtained, commerce wherein you fear decline, and dwellings with which you are pleased are more beloved to you than Allah and His Messenger and striving in His cause, then wait until Allah executes His command. And Allah does not guide the defiantly disobedient people.'" },
    { number: "9:25", arabic: "Placeholder", lao: "Placeholder", english: "Allah has already given you victory in many regions and [even] on the day of Hunayn, when your great number pleased you, but it did not avail you at all, and the earth was constrained upon you for all its vastness; then you turned back, fleeing." },
    { number: "9:26", arabic: "Placeholder", lao: "Placeholder", english: "Then Allah sent down His tranquillity upon His Messenger and upon the believers and sent down soldiers angels whom you did not see and punished those who disbelieved. And that is the recompense of the disbelievers." },
    { number: "9:27", arabic: "Placeholder", lao: "Placeholder", english: "Then Allah will accept repentance after that for whom He wills; and Allah is Forgiving and Merciful." },
    { number: "9:28", arabic: "Placeholder", lao: "Placeholder", english: "O you who have believed, indeed the polytheists are unclean, so let them not approach al-Masjid al-Haram after this, their [final] year. And if you fear privation, Allah will enrich you from His bounty if He wills. Indeed, Allah is Knowing and Wise." },
    { number: "9:29", arabic: "Placeholder", lao: "Placeholder", english: "Fight those who do not believe in Allah or in the Last Day and who do not consider unlawful what Allah and His Messenger have made unlawful and who do not adopt the religion of truth from those who were given the Scripture - [fight] until they give the jizyah willingly while they are humbled." },
    { number: "9:30", arabic: "Placeholder", lao: "Placeholder", english: "The Jews say, 'Ezra is the son of Allah'; and the Christians say, 'The Messiah is the son of Allah.' That is their statement from their mouths; they imitate the saying of those who disbelieved before [them]. May Allah destroy them; how are they deluded?" },
    { number: "9:31", arabic: "Placeholder", lao: "Placeholder", english: "They have taken their scholars and monks as lords besides Allah, and [also] the Messiah, the son of Mary. And they were not commanded except to worship one God; there is no deity except Him. Exalted is He above whatever they associate with Him." },
    { number: "9:32", arabic: "Placeholder", lao: "Placeholder", english: "They want to extinguish the light of Allah with their mouths, but Allah refuses except to perfect His light, although the disbelievers dislike it." },
    { number: "9:33", arabic: "Placeholder", lao: "Placeholder", english: "It is He who has sent His Messenger with guidance and the religion of truth to manifest it over all religion, although those who associate others with Allah dislike it." },
    { number: "9:34", arabic: "Placeholder", lao: "Placeholder", english: "O you who have believed, indeed many of the scholars and the monks devour the wealth of people unjustly and avert [them] from the way of Allah. And those who hoard gold and silver and spend it not in the way of Allah - give them tidings of a painful punishment." },
    { number: "9:35", arabic: "Placeholder", lao: "Placeholder", english: "The Day when it will be heated in the fire of Hell and seared therewith will be their foreheads, their flanks, and their backs, [it will be said], 'This is what you hoarded for yourselves, so taste what you used to hoard.'" },
    { number: "9:36", arabic: "Placeholder", lao: "Placeholder", english: "Indeed, the number of months with Allah is twelve [lunar] months in the register of Allah [from] the day He created the heavens and the earth; of these, four are sacred. That is the correct religion, so do not wrong yourselves during them. And fight against the polytheists collectively as they fight against you collectively. And know that Allah is with the righteous [who fear Him]." },
    { number: "9:37", arabic: "Placeholder", lao: "Placeholder", english: "Indeed, the postponing [of restriction within sacred months] is an increase in disbelief by which those who have disbelieved are led astray. They make it lawful one year and unlawful another year to correspond to the number made unlawful by Allah and [thus] make lawful what Allah has made unlawful. Made pleasing to them is the evil of their deeds; and Allah does not guide the disbelieving people." },
    { number: "9:38", arabic: "Placeholder", lao: "Placeholder", english: "O you who have believed, what is [the matter] with you that, when you are told to go forth in the cause of Allah, you adhere heavily to the earth? Are you satisfied with the life of this world rather than the Hereafter? But the enjoyment of worldly life is not, compared to the Hereafter, except a [very] little." },
    { number: "9:39", arabic: "Placeholder", lao: "Placeholder", english: "If you do not go forth, He will punish you with a painful punishment and will replace you with another people, and you will not harm Him at all. And Allah is over all things competent." },
    { number: "9:40", arabic: "Placeholder", lao: "Placeholder", english: "If you do not aid the Prophet - Allah has already aided him when those who disbelieved had driven him out [of Makkah] as one of two, when they were in the cave and he said to his companion, 'Do not grieve; indeed Allah is with us.' And Allah sent down his tranquillity upon him and supported him with angels you did not see and made the word of those who disbelieved the lowest, while the word of Allah - that is the highest. And Allah is Exalted in Might and Wise." },
    { number: "9:41", arabic: "Placeholder", lao: "Placeholder", english: "Go forth, whether light or heavy, and strive with your wealth and your lives in the cause of Allah. That is better for you, if you only knew." },
    { number: "9:42", arabic: "Placeholder", lao: "Placeholder", english: "Had it been an easy gain and a moderate trip, the hypocrites would have followed you, but distant to them was the journey. And they will swear by Allah, 'If we were able, we would have gone forth with you.' They destroy themselves, and Allah knows that they are indeed liars." },
    { number: "9:43", arabic: "Placeholder", lao: "Placeholder", english: "May Allah pardon you, [O Muhammad]; why did you give them permission [to remain behind] until it was clear to you who were truthful and you knew the liars?" },
    { number: "9:44", arabic: "Placeholder", lao: "Placeholder", english: "Those who believe in Allah and the Last Day would not ask permission of you to be excused from striving with their wealth and their lives. And Allah is Knowing of those who fear Him." },
    { number: "9:45", arabic: "Placeholder", lao: "Placeholder", english: "They who do not believe in Allah and the Last Day would only ask you for permission [to stay back], and their hearts have doubted, and they, in their doubt, are hesitating." },
    { number: "9:46", arabic: "Placeholder", lao: "Placeholder", english: "And if they had intended to go forth, they would have prepared for it [some] preparation. But Allah disliked their being sent, so He kept them back, and it was said, 'Remain with those who remain [behind].'" },
    { number: "9:47", arabic: "Placeholder", lao: "Placeholder", english: "Had they gone forth with you, they would not have increased you except in confusion, and they would have fallen into your midst seeking [to cause] fitnah [trial, discord] among you. And among you are avid listeners to them. And Allah is Knowing of the wrongdoers." },
    { number: "9:48", arabic: "Placeholder", lao: "Placeholder", english: "They had already desired trial before and had turned matters upside down for you until the truth came and the command of Allah appeared, while they were averse." },
    { number: "9:49", arabic: "Placeholder", lao: "Placeholder", english: "And among them is he who says, 'Permit me [to remain at home] and do not put me to trial.' Unquestionably, into trial they have fallen. And indeed, Hell will encompass the disbelievers." },
    { number: "9:50", arabic: "Placeholder", lao: "Placeholder", english: "If good befalls you, it distresses them; but if disaster strikes you, they say, 'We took our precaution beforehand,' and they turn away rejoicing." },
    { number: "9:51", arabic: "Placeholder", lao: "Placeholder", english: "Say, 'Never will we be struck except by what Allah has decreed for us; He is our protector.' And upon Allah let the believers rely." },
    { number: "9:52", arabic: "Placeholder", lao: "Placeholder", english: "Say, 'Do you await for us except one of the two best things while we await for you that Allah will afflict you with punishment from Himself or at our hands? So wait; indeed, we are waiting with you.'" },
    { number: "9:53", arabic: "Placeholder", lao: "Placeholder", english: "Say, 'Spend willingly or unwillingly; never will it be accepted from you. Indeed, you have been a defiantly disobedient people.'" },
    { number: "9:54", arabic: "Placeholder", lao: "Placeholder", english: "And what prevents their expenditures from being accepted from them but that they have disbelieved in Allah and in His Messenger and that they do not come to prayer except while they are lazy and that they do not spend except while they are unwilling." },
    { number: "9:55", arabic: "Placeholder", lao: "Placeholder", english: "So let not their wealth or their children impress you. Allah only intends to punish them through them in worldly life and that their souls should depart while they are disbelievers." },
    { number: "9:56", arabic: "Placeholder", lao: "Placeholder", english: "And they swear by Allah that they are from among you while they are not from among you; but they are a people who are afraid." },
    { number: "9:57", arabic: "Placeholder", lao: "Placeholder", english: "If they could find a refuge or some caves or any place to enter [and hide], they would turn to it while they run heedlessly." },
    { number: "9:58", arabic: "Placeholder", lao: "Placeholder", english: "And among them are some who criticize you concerning the [distribution of] charities. If they are given from them, they are pleased; but if they are not given from them, at once they become angry." },
    { number: "9:59", arabic: "Placeholder", lao: "Placeholder", english: "If only they had been satisfied with what Allah and His Messenger gave them and said, 'Sufficient for us is Allah ; Allah will give us of His bounty, and [so will] His Messenger; indeed, we are desirous toward Allah.'" },
    { number: "9:60", arabic: "Placeholder", lao: "Placeholder", english: "Zakah expenditures are only for the poor and for the needy and for those employed to collect [zakah] and for bringing hearts together [for Islam] and for freeing captives [or slaves] and for those in debt and for the cause of Allah and for the [stranded] traveler - an obligation [imposed] by Allah. And Allah is Knowing and Wise." },
    { number: "9:61", arabic: "Placeholder", lao: "Placeholder", english: "And among them are those who abuse the Prophet and say, 'He is an ear.' Say, '[It is] an ear of goodness for you that believes in Allah and gives credence to the believers and is a mercy to those who believe among you.' And those who abuse the Messenger of Allah - for them is a painful punishment." },
    { number: "9:62", arabic: "Placeholder", lao: "Placeholder", english: "They swear by Allah to you [Muslims] to satisfy you. But Allah and His Messenger are more worthy for them to satisfy, if they should be believers." },
    { number: "9:63", arabic: "Placeholder", lao: "Placeholder", english: "Do they not know that whoever opposes Allah and His Messenger - that for him is the fire of Hell, wherein he will abide eternally? That is the great disgrace." },
    { number: "9:64", arabic: "Placeholder", lao: "Placeholder", english: "The hypocrites are apprehensive lest a surah be revealed about them, informing them of what is in their hearts. Say, 'Mock [as you wish]; indeed, Allah will expose that which you fear.'" },
    { number: "9:65", arabic: "Placeholder", lao: "Placeholder", english: "And if you ask them, they will surely say, 'We were only conversing and playing.' Say, 'Is it Allah and His verses and His Messenger that you were mocking?'" },
    { number: "9:66", arabic: "Placeholder", lao: "Placeholder", english: "Make no excuse; you have disbelieved after your belief. If We pardon one faction of you, We will punish another faction because they were criminals." },
    { number: "9:67", arabic: "Placeholder", lao: "Placeholder", english: "The hypocrite men and hypocrite women are of one another. They enjoin what is wrong and forbid what is right and close their hands. They have forgotten Allah, so He has forgotten them. Indeed, the hypocrites - it is they who are the defiantly disobedient." },
    { number: "9:68", arabic: "Placeholder", lao: "Placeholder", english: "Allah has promised the hypocrite men and hypocrite women and the disbelievers the fire of Hell, wherein they will abide eternally. It is sufficient for them. And Allah has cursed them, and for them is an enduring punishment." },
    { number: "9:69", arabic: "Placeholder", lao: "Placeholder", english: "[You disbelievers are] like those before you; they were stronger than you in power and more abundant in wealth and children. They enjoyed their portion, and you have enjoyed your portion as those before you enjoyed their portion, and you have engaged in idle talk like that in which they engaged. [For] those, their deeds have become worthless in this world and the Hereafter, and it is they who are the losers." },
    { number: "9:70", arabic: "Placeholder", lao: "Placeholder", english: "Has there not reached them the news of those before them - the people of Noah and 'Aad and Thamud and the people of Abraham and the companions of Madyan and the towns overturned? Their messengers came to them with clear proofs. And Allah would never have wronged them, but they were wronging themselves." },
    { number: "9:71", arabic: "Placeholder", lao: "Placeholder", english: "The believing men and believing women are allies of one another. They enjoin what is right and forbid what is wrong and establish prayer and give zakah and obey Allah and His Messenger. Those - Allah will have mercy upon them. Indeed, Allah is Exalted in Might and Wise." },
    { number: "9:72", arabic: "Placeholder", lao: "Placeholder", english: "Allah has promised the believing men and believing women gardens beneath which rivers flow, wherein they will abide eternally, and pleasant dwellings in gardens of perpetual residence; but approval from Allah is greater. It is that which is the great attainment." },
    { number: "9:73", arabic: "Placeholder", lao: "Placeholder", english: "O Prophet, fight against the disbelievers and the hypocrites and be harsh upon them. And their refuge is Hell, and wretched is the destination." },
    { number: "9:74", arabic: "Placeholder", lao: "Placeholder", english: "They swear by Allah that they did not say [anything wrong], but they had certainly said the word of disbelief and disbelieved after their [pretense of] Islam and planned that which they did not attain. And they were not resentful except [for the fact] that Allah and His Messenger had enriched them of His bounty. So if they repent, it is better for them; but if they turn away, Allah will punish them with a painful punishment in this world and the Hereafter. And there is not for them on earth any protector or helper." },
    { number: "9:75", arabic: "Placeholder", lao: "Placeholder", english: "And among them are those who made a covenant with Allah, [saying], 'If He should give us from His bounty, we will surely spend in charity, and we will surely be among the righteous.'" },
    { number: "9:76", arabic: "Placeholder", lao: "Placeholder", english: "But when he gave them from His bounty, they were stingy with it and turned away while they were refusing." },
    { number: "9:77", arabic: "Placeholder", lao: "Placeholder", english: "So He penalized them with hypocrisy in their hearts until the Day they will meet Him - because they failed Allah in what they promised Him and because they were lying." },
    { number: "9:78", arabic: "Placeholder", lao: "Placeholder", english: "Did they not know that Allah knows their secrets and their private conversations and that Allah is a Knower of the unseen?" },
    { number: "9:79", arabic: "Placeholder", lao: "Placeholder", english: "Those who criticize the contributors among the believers concerning [their] charities and [criticize] the ones who find nothing [to spend] except their effort, so they ridicule them - Allah will ridicule them, and for them is a painful punishment." },
    { number: "9:80", arabic: "Placeholder", lao: "Placeholder", english: "Ask forgiveness for them, [O Muhammad], or do not ask forgiveness for them. If you should ask forgiveness for them seventy times - never will Allah forgive them. That is because they disbelieved in Allah and His Messenger, and Allah does not guide the defiantly disobedient people." },
    { number: "9:81", arabic: "Placeholder", lao: "Placeholder", english: "Those who remained behind rejoiced in their staying [at home] after [the departure of] the Messenger of Allah and disliked to strive with their wealth and their lives in the cause of Allah and said, 'Do not go forth in the heat.' Say, 'The fire of Hell is more intensive in heat' - if they would but understand." },
    { number: "9:82", arabic: "Placeholder", lao: "Placeholder", english: "So let them laugh a little and then weep much as recompense for what they used to earn." },
    { number: "9:83", arabic: "Placeholder", lao: "Placeholder", english: "If Allah should return you to a faction of them [after the expedition] and then they ask your permission to go out [to battle], say, 'You will not go out with me, ever, and you will never fight with me an enemy. Indeed, you were content with sitting back the first time, so sit back with those who stay behind.'" },
    { number: "9:84", arabic: "Placeholder", lao: "Placeholder", english: "And do not pray [the funeral prayer, O Muhammad], over any of them who has died - ever - or stand at his grave. Indeed, they disbelieved in Allah and His Messenger and died while they were defiantly disobedient." },
    { number: "9:85", arabic: "Placeholder", lao: "Placeholder", english: "And let not their wealth and their children impress you. Allah only intends to punish them through them in this world and that their souls should depart while they are disbelievers." },
    { number: "9:86", arabic: "Placeholder", lao: "Placeholder", english: "And when a surah was revealed [enjoining them] to believe in Allah and strive with His Messenger, those of wealth among them asked your permission [to stay back] and said, 'Leave us to be with them who sit.'" },
    { number: "9:87", arabic: "Placeholder", lao: "Placeholder", english: "They were content to be with those who stay behind, and their hearts were sealed over, so they do not understand." },
    { number: "9:88", arabic: "Placeholder", lao: "Placeholder", english: "But the Messenger and those who believed with him strove with their wealth and their lives. And it is those for whom are the good things, and it is those who are the successful." },
    { number: "9:89", arabic: "Placeholder", lao: "Placeholder", english: "Allah has prepared for them gardens beneath which rivers flow, wherein they will abide eternally. That is the great attainment." },
    { number: "9:90", arabic: "Placeholder", lao: "Placeholder", english: "And those with excuses among the bedouins came to be permitted [to remain behind], and they who were false to Allah and His Messenger sat [at home]. There will strike those who disbelieved among them a painful punishment." },
    { number: "9:91", arabic: "Placeholder", lao: "Placeholder", english: "There is not upon the weak or upon the ill or upon those who do not find anything to spend any blame when they are sincere to Allah and His Messenger. There is not upon the doers of good any cause [for blame]. And Allah is Forgiving and Merciful." },
    { number: "9:92", arabic: "Placeholder", lao: "Placeholder", english: "Nor [is there blame] upon those who, when they came to you that you might give them mounts, you said, 'I can find nothing for you to ride upon.' They turned back while their eyes overflowed with tears out of grief that they could not find something to spend [for the cause of Allah]." },
    { number: "9:93", arabic: "Placeholder", lao: "Placeholder", english: "The cause [for blame] is only upon those who ask permission of you while they are rich. They are content to be with those who stay behind, and Allah has sealed over their hearts, so they do not know." },
    { number: "9:94", arabic: "Placeholder", lao: "Placeholder", english: "They will make excuses to you when you have returned to them. Say, 'Make no excuse - never will we believe you. Allah has already informed us of your news. And Allah will observe your deeds, and [so will] His Messenger; then you will be returned to the Knower of the unseen and the witnessed, and He will inform you of what you used to do.'" },
    { number: "9:95", arabic: "Placeholder", lao: "Placeholder", english: "They will swear by Allah to you when you return to them that you would leave them alone. So leave them alone; indeed, they are evil; and their refuge is Hell as a recompense for what they used to earn." },
    { number: "9:96", arabic: "Placeholder", lao: "Placeholder", english: "They swear to you that you might be satisfied with them. But if you should be satisfied with them - indeed, Allah is not satisfied with a defiantly disobedient people." },
    { number: "9:97", arabic: "Placeholder", lao: "Placeholder", english: "The bedouins are stronger in disbelief and hypocrisy and more likely not to know the limits of what [laws] Allah has revealed to His Messenger. And Allah is Knowing and Wise." },
    { number: "9:98", arabic: "Placeholder", lao: "Placeholder", english: "And among the bedouins are some who consider what they spend as a loss and await for you turns of misfortune. Upon them will be the misfortune of evil. And Allah is Hearing and Knowing." },
    { number: "9:99", arabic: "Placeholder", lao: "Placeholder", english: "And among the bedouins are some who believe in Allah and the Last Day and consider what they spend as means of nearness to Allah and of [obtaining] the invocations of the Messenger. Unquestionably, it is a means of nearness for them. Allah will admit them to His mercy. Indeed, Allah is Forgiving and Merciful." },
    { number: "9:100", arabic: "Placeholder", lao: "Placeholder", english: "And the first forerunners [in the faith] among the Muhajireen and the Ansar and those who followed them with good conduct - Allah is pleased with them and they are pleased with Him, and He has prepared for them gardens beneath which rivers flow, wherein they will abide forever. That is the great attainment." },
    { number: "9:101", arabic: "Placeholder", lao: "Placeholder", english: "And among those around you of the bedouins are hypocrites, and [also] from the people of Madinah. They have persisted in hypocrisy. You, [O Muhammad], do not know them, [but] We know them. We will punish them twice [in this world]; then they will be returned to a great punishment." },
    { number: "9:102", arabic: "Placeholder", lao: "Placeholder", english: "And [there are] others who have acknowledged their sins. They had mixed a righteous deed with another that was bad. Perhaps Allah will turn to them in forgiveness. Indeed, Allah is Forgiving and Merciful." },
    { number: "9:103", arabic: "Placeholder", lao: "Placeholder", english: "Take, [O, Muhammad], from their wealth a charity by which you purify them and cause them increase, and invoke [Allah's blessings] upon them. Indeed, your invocations are reassurance for them. And Allah is Hearing and Knowing." },
    { number: "9:104", arabic: "Placeholder", lao: "Placeholder", english: "Do they not know that it is Allah who accepts repentance from His servants and receives charities and that it is Allah who is the Accepting of repentance, the Merciful?" },
    { number: "9:105", arabic: "Placeholder", lao: "Placeholder", english: "And say, 'Do [as you will], for Allah will see your deeds, and [so, will] His Messenger and the believers. And you will be returned to the Knower of the unseen and the witnessed, and He will inform you of what you used to do.'" },
    { number: "9:106", arabic: "Placeholder", lao: "Placeholder", english: "And [there are] others deferred until the command of Allah - whether He will punish them or whether He will turn to them in forgiveness. And Allah is Knowing and Wise." },
    { number: "9:107", arabic: "Placeholder", lao: "Placeholder", english: "And [there are] those [hypocrites] who took for themselves a mosque for causing harm and disbelief and division among the believers and as a station for whoever waged war against Allah and His Messenger before. And they will surely swear, 'We intended only the best.' And Allah testifies that they are indeed liars." },
    { number: "9:108", arabic: "Placeholder", lao: "Placeholder", english: "Do not stand [for prayer] within it - ever. A mosque founded on righteousness from the first day is more worthy for you to stand in. Within it are men who love to purify themselves; and Allah loves those who purify themselves." },
    { number: "9:109", arabic: "Placeholder", lao: "Placeholder", english: "Then is one who laid the foundation of his building on righteousness [with fear] from Allah and [seeking] His approval better or one who laid the foundation of his building on the edge of a bank about to collapse, so it collapsed with him into the fire of Hell? And Allah does not guide the wrongdoing people." },
    { number: "9:110", arabic: "Placeholder", lao: "Placeholder", english: "Their building which they built will not cease to be a [cause of] skepticism in their hearts until their hearts are cut into pieces. And Allah is Knowing and Wise." },
    { number: "9:111", arabic: "Placeholder", lao: "Placeholder", english: "Indeed, Allah has purchased from the believers their lives and their properties [in exchange] for that they will have Paradise. They fight in the cause of Allah, so they kill and are killed. [It is] a true promise [binding] upon Him in the Torah and the Gospel and the Qur'an. And who is truer to his covenant than Allah? So rejoice in your transaction which you have contracted. And it is that which is the great attainment." },
    { number: "9:112", arabic: "Placeholder", lao: "Placeholder", english: "[Are] the repentant, the worshippers, the praisers [of Allah], the travelers [for His cause], the bowers [in prayer], the prostrators [in prayer], the enjoiners of what is right and the forbidder of what is wrong, and the observers of the limits set by Allah. And give good tidings to the believers." },
    { number: "9:113", arabic: "Placeholder", lao: "Placeholder", english: "It is not for the Prophet and those who have believed to ask forgiveness for the polytheists, even if they were relatives, after it has become clear to them that they are companions of Hellfire." },
    { number: "9:114", arabic: "Placeholder", lao: "Placeholder", english: "And the request of forgiveness of Abraham for his father was only because of a promise he had made to him. But when it became clear to him that he was an enemy to Allah, he disassociated himself from him. Indeed, Abraham was compassionate and forbearing." },
    { number: "9:115", arabic: "Placeholder", lao: "Placeholder", english: "And Allah would not let a people stray after He has guided them until He makes clear to them what they should avoid. Indeed, Allah is Knowing of all things." },
    { number: "9:116", arabic: "Placeholder", lao: "Placeholder", english: "Indeed, to Allah belongs the dominion of the heavens and the earth; He gives life and causes death. And you have not besides Allah any protector or any helper." },
    { number: "9:117", arabic: "Placeholder", lao: "Placeholder", english: "Allah has already forgiven the Prophet and the Muhajireen and the Ansar who followed him in the hour of difficulty after the hearts of a party of them had almost inclined [to doubt], and then He forgave them. Indeed, He was to them Kind and Merciful." },
    { number: "9:118", arabic: "Placeholder", lao: "Placeholder", english: "And [He also forgave] the three who were left behind [and regretted their error] to the point that the earth closed in on them in spite of its vastness and their souls confined them and they were certain that there is no refuge from Allah except in Him. Then He turned to them so they could repent. Indeed, Allah is the Accepting of repentance, the Merciful." },
    { number: "9:119", arabic: "Placeholder", lao: "Placeholder", english: "O you who have believed, fear Allah and be with those who are true." },
    { number: "9:120", arabic: "Placeholder", lao: "Placeholder", english: "It was not [proper] for the people of Madinah and those surrounding them of the bedouins that they should remain behind the Messenger of Allah or prefer themselves over his life. That is because they are not afflicted by thirst or fatigue or hunger in the cause of Allah, nor do they tread on any ground that enrages the disbelievers, nor do they inflict upon an enemy any infliction but that is registered for them as a righteous deed. Indeed, Allah does not allow to be lost the reward of the doers of good." },
    { number: "9:121", arabic: "Placeholder", lao: "Placeholder", english: "Nor do they spend an expenditure, small or large, or cross a valley but that it is registered for them that Allah may reward them for the best of what they were doing." },
    { number: "9:122", arabic: "Placeholder", lao: "Placeholder", english: "And it is not for the believers to go forth [to battle] all at once. For there should separate from every division of them a group [remaining] to obtain understanding in the religion and warn their people when they return to them that they might be cautious." },
    { number: "9:123", arabic: "Placeholder", lao: "Placeholder", english: "O you who have believed, fight those adjacent to you of the disbelievers and let them find in you harshness. And know that Allah is with the righteous." },
    { number: "9:124", arabic: "Placeholder", lao: "Placeholder", english: "And whenever a surah is revealed, there are among the hypocrites those who say, 'Which of you has this increased in faith?' As for those who believed, it has increased them in faith, and they rejoice." },
    { number: "9:125", arabic: "Placeholder", lao: "Placeholder", english: "But as for those in whose hearts is disease, it has added filth to their filth, and they die while they are disbelievers." },
    { number: "9:126", arabic: "Placeholder", lao: "Placeholder", english: "Do they not see that they are tried every year once or twice but then they do not repent nor do they remember?" },
    { number: "9:127", arabic: "Placeholder", lao: "Placeholder", english: "And whenever a surah is revealed, they look at each other, [saying], 'Does anyone see you?' and then they turn away. Allah has turned away their hearts because they are a people who do not understand." },
    { number: "9:128", arabic: "Placeholder", lao: "Placeholder", english: "There has certainly come to you a Messenger from among yourselves. Grievous to him is what you suffer; [he is] concerned over you and to the believers is kind and merciful." },
    { number: "9:129", arabic: "Placeholder", lao: "Placeholder", english: "But if they turn away, [O Muhammad], say, 'Sufficient for me is Allah ; there is no deity except Him. On Him I have relied, and He is the Lord of the Great Throne.'" }
];

// NOTE: Omitting full verse list for brevity, but all 129 verses are included.

export default function SurahAtTawbahView({ goBack }: SurahAtTawbahViewProps) {
  const [searchQuery, setSearchQuery] = useState('');

  const filteredVerses = verses.filter(verse =>
    verse.number.includes(searchQuery) ||
    verse.lao.toLowerCase().includes(searchQuery.toLowerCase()) ||
    verse.english.toLowerCase().includes(searchQuery.toLowerCase()) ||
    verse.arabic.includes(searchQuery)
  );

  return (
    <div className="flex flex-col h-screen">
       <header className="flex items-center p-4 sticky top-0 bg-background z-10 border-b">
        <Button variant="ghost" size="icon" onClick={goBack} className="mr-2 shrink-0">
          <ArrowLeft className="w-6 h-6 text-foreground" />
          <span className="sr-only">Back</span>
        </Button>
        <div className="relative w-full">
          <Input
            type="text"
            placeholder="ຄົ້ນຫາອາຍັດໃນ ສູຣໍ ອັດເຕົາບະ..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full"
          />
        </div>
      </header>
      <main className="flex-grow overflow-y-auto p-4">
        {filteredVerses.length > 0 ? (
          filteredVerses.map(v => <VerseCard key={v.number} {...v} />)
        ) : (
          <p className="text-center text-muted-foreground">No Ayah found.</p>
        )}
        <SummaryCard title="Summary">
          This Surah is unique as it does not begin with the 'Bismillah'. It deals with the disassociation from polytheists who repeatedly broke their treaties, the conduct of warfare, hypocrisy, the importance of sincere repentance, and the characteristics of true believers.
        </SummaryCard>
      </main>
    </div>
  );
}
